In [2]:
import numpy as np
twoDArray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9] ])
print(twoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [9]:
def searchTDArray(array, value):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j]==value:
                return "value located at index position "+str(i)+","+str(j)
    return "Element not found"


In [11]:
print(searchTDArray(twoDArray, ))

Element not found
